gallery/urls.py
from django.urls import re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    re_path('^$', views.home, name = 'home'),
    re_path(r'^search/', views.search_results, name='search_results'),
    re_path(r'^category/', views.categories, name= "categories"),
    re_path(r'^location/', views.location, name='location'),    
]
if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

mygallery/urls.py
from django.contrib import admin
from django.urls import re_path, include

urlpatterns = [
    re_path('admin/', admin.site.urls),
    re_path(r'', include('gallery.urls')),
    

]

gallery/models.py
from django.db import models
import datetime as dt


class Image(models.Model):
    name = models.CharField(max_length=20)
    description = models.CharField(max_length= 40)
    image = models.ImageField(upload_to = 'images/', null=True, blank=True)
    pub_date = models.DateTimeField(auto_now_add=True)
    categoryName = models.ForeignKey('category', on_delete=models.CASCADE)
    location = models.ForeignKey('Location', on_delete=models.CASCADE)
    
    def save_image(self): 
        self.save() 
    def delete_image(self): 
        self.delete() 
    
    @classmethod
    def all_images(cls): 
        images= Image.objects.all() 
        return images
    
    @classmethod
    def search_by_category(cls, search_term):
        posts = cls.objects.filter(cat_name__icontains=search_term)
        return posts

    def __str__(self): 
        return self.name 
    @classmethod
    def update_image(cls,current_img,new_img):
        updated_img = Image.objects.filter(image_name=current_img).update(name=new_img)
        return updated_img

    @classmethod
    def filter_by_location(cls,location):
        filtered_img = cls.objects.filter(location__location_name__icontains=location)
        return filtered_img
     
class Location(models.Model):
    location_name = models.CharField(max_length=20) 
   
    
    def save_location(self): 
        self.save() 
    def delete_location(self): 
        self.delete() 
    def __str__(self): 
        return self.location_name 
 
class category(models.Model):
    cat_name =models.CharField(max_length=20)
    def save_category(self):
        self.save()

    def delete_category(self):
        self.delete()
        
    @classmethod
    def search_by_category(cls, search_term):
        posts = cls.objects.filter(cat_name__icontains=search_term)
        return posts
    
    def __str__(self):
        return self.cat_name
    
  

     

gallery/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Image, category, Location
from django.db.models import Q

# Create your views here.
def home(request):   
    images = Image.all_images().order_by('-pub_date')
    return render(request, 'index.html'  , {"images": images})
def search_results(request):

    if 'category' in request.GET and request.GET["category"]:
        search_term = request.GET.get("category")
        searched_images = category.search_by_category(search_term)
        message = f"{search_term}"

        return render(request, 'search.html',{"message":message,"categories": searched_images})

    else:
        message = "You haven't searched for any term"
        return render(request, 'search.html',{"message":message})
    
#  def search_results(request):
#     if 'category' in request.GET and request.GET["category"]:
#         search_term = request.GET.get("category")
#         searched_category = Image.search_by_category(search_term)
#         message = f"{search_term}"

#         return render(request, 'search.html',{"message":message,"categories":searched_category})

#     else:
#         message = "You haven't searched for any term"
#         return render(request, 'search.html',{"message":message})
    
def categories(request):
    categories = category.objects.all()

    context = {
        'categories': categories,
    }
    return render(request, 'category.html', context)    

def location(request):
    location = Location.objects.all()

    context = {
        'locations': location,
    }
    return render(request, 'location.html', context) 
    
    
    

gallery/templates/base.html
{% load bootstrap5 %} {% load static%}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
  </head>
  {% load static %} {% block styles %} <link rel="stylesheet" type="text/css"
  href="{% static "fontawesome/css/all.min.css" %}" />
  <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
    crossorigin="anonymous"
  />
  <link rel="stylesheet" href="{% static 'css/style.css' %}" />

  {% endblock %}

  <body>
    {%include 'navbar.html' %} {% block content %}
    <p></p>
    {%endblock%} {%include 'footer.html' %} {%block scripts%}
    <script src="{% static 'js/script.js' %}"></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>
    {% bootstrap_javascript %} {%endblock%}
  </body>
</html>

gallery/templates/category.html
{%extends 'base.html'%} {% block content %}
<div class="row">
  <div class="col-lg-1 dash"></div>
  <div class="col-lg-10 col-md-4 col-sm-12 posts">
    {% for category in categories%}
    <p></p>
    <p class="category">
      <span>Category:</span> {{ category.cat_name | capfirst}}
    </p>
    <div class="col-lg-10 posts">
      {% for image in category.image_set.all %}

      <div class="card" id="postcat">
        <img class="card-img-top" src="{{image.image.url}}" alt="" />
        <div class="card-body">
          <p>{{image.description}}</p>
          <button
            type="button"
            class="btn btn-primary"
            data-bs-toggle="modal"
            data-bs-target="#myModal{{image.id}}"
            data-bs-target="#exampleModal"
          >
            VIEW DETAILS
          </button>
        </div>
      </div>
      {% endfor %} {% for image in category.image_set.all %}

      <div
        class="modal fade"
        id="myModal{{image.id}}"
        tabindex="-1"
        aria-labelledby="exampleModalLabel"
        aria-hidden="true"
      >
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button
                type="button"
                class="btn-close"
                data-bs-dismiss="modal"
                aria-label="Close"
              ></button>
            </div>
            <div class="modal-body">
              <img
                class="card-img-top myImg"
                src="{{image.image.url}}"
                alt=""
              />
              <p>{{image.description}}</p>

              <p>
                <i class="fas fa-search-location"></i>

                {{image.location}}
              </p>
              <p>
                <i class="fas fa-calendar-check"></i>

                {{image.pub_date}}
              </p>
               <a
                name=""
                id="copyUrl"
                onclick="copyUrl(event)"
                class="btn btn-primary"
                href="https://vicsgallery.herokuapp.com{{image.image.url}}"
                role="button"
              >
                <i class="fa fa-copy"></i
              ></a>
            </div>
            <div class="modal-footer">
              <button
                type="button"
                class="btn btn-secondary"
                data-bs-dismiss="modal"
              >
                CLOSE
              </button>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    {% endfor %}
    </div>
    <div class="col-lg-1 dash"></div>
  </div>
  {% endblock %}
</div>

gallery/templates/index.html
{%extends 'base.html'%}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
  </head>
  <body>
    {%block content%}

    <div class="row">
      <div class="col-lg-1 dash"></div>
      <div class="col-lg-10 col-md-4 col-sm-12 posts">
        {%for image in images%}

        <div class="card" id="post">
          <img
            class="card-img-top"
            data-bs-toggle="modal"
            src="{{image.image.url}}"
            alt=""
          />
          <div class="card-body">
            <p>{{image.description}}</p>

            <button
              type="button"
              class="btn btn-primary"
              data-bs-toggle="modal"
              data-bs-target="#myModal{{image.id}}"
              data-bs-target="#exampleModal"
            >
              VIEW DETAILS
            </button>
          </div>
        </div>
        {%endfor%} {%for image in images%}

        <div
          class="modal fade"
          tabindex="-1"
          id="myModal{{image.id}}"
          aria-labelledby="exampleModalLabel"
          aria-hidden="true"
        >
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button
                  type="button"
                  class="btn-close"
                  data-bs-dismiss="modal"
                  aria-label="Close"
                ></button>
              </div>
              <div class="modal-body">
                <img
                  class="card-img-top myImg"
                  src="{{image.image.url}}"
                  alt=""
                />
                <p>{{image.description}}</p>

                <p>
                  <i class="fas fa-search-location"></i>

                  {{image.location}}
                </p>
                <p>
                  <i class="fas fa-calendar-check"></i>

                  {{image.pub_date}}
                </p>
                <a
                  name=""
                  id="copyUrl"
                  onclick="copyUrl(event)"
                  class="btn btn-primary"
                  href="https://vicsgallery.herokuapp.com{{image.image.url}}"
                  role="button"
                >
                  <i class="fa fa-copy"></i
                ></a>
              </div>
              <div class="modal-footer">
                <button
                  type="button"
                  class="btn btn-secondary"
                  data-bs-dismiss="modal"
                >
                  CLOSE
                </button>
              </div>
            </div>
          </div>
        </div>
        {%endfor%}
      </div>
      <div class="col-lg-1 dash"></div>
    </div>

    {%endblock%}
  </body>
</html>

gallery/templates/location.html
{%extends 'base.html'%} {% block content %}
<div class="row">
  <div class="col-lg-1 dash"></div>
  <div class="col-lg-10 col-md-4 col-sm-12 posts">
    {% for location in locations%}

    <p class="category">
      <span>Location:</span> {{ location.location_name | capfirst}}
    </p>
    <div class="col-lg-10 posts">
      {% for image in location.image_set.all %}

      <div class="card" id="postcat">
        <img class="card-img-top" src="{{image.image.url}}" alt="" />
        <div class="card-body">
          <p>{{image.description}}</p>
          <button
            type="button"
            class="btn btn-primary"
            data-bs-toggle="modal"
            data-bs-target="#myModal{{image.id}}"
            data-bs-target="#exampleModal"
          >
            VIEW DETAILS
          </button>
        </div>
      </div>
      {% endfor %} {% for image in location.image_set.all %}

      <div
        class="modal fade"
        id="myModal{{image.id}}"
        tabindex="-1"
        aria-labelledby="exampleModalLabel"
        aria-hidden="true"
      >
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button
                type="button"
                class="btn-close"
                data-bs-dismiss="modal"
                aria-label="Close"
              ></button>
            </div>
            <div class="modal-body">
              <img
                class="card-img-top myImg"
                src="{{image.image.url}}"
                alt=""
              />
              <p>{{image.description}}</p>

              <p>
                <i class="fas fa-search-location"></i>

                {{image.location}}
              </p>
              <p>
                <i class="fas fa-calendar-check"></i>

                {{image.pub_date}}
              </p>
              <a
                name=""
                id="copyUrl"
                onclick="copyUrl(event)"
                class="btn btn-primary"
                href="https://vicsgallery.herokuapp.com{{image.image.url}}"
                role="button"
              >
                <i class="fa fa-copy"></i
              ></a>
            </div>
            <div class="modal-footer">
              <button
                type="button"
                class="btn btn-secondary"
                data-bs-dismiss="modal"
              >
                CLOSE
              </button>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    {% endfor %}
  </div>
  <div class="col-lg-1 dash"></div>

  {% endblock %}
</div>

gallery/templates/navbar.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{%url "home"%}">My Gallery</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{%url "home"%}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{%url "categories"%}">Category</a>
            </li>
             <li class="nav-item">
              <a class="nav-link" href="{%url "location"%}">Location</a>
            </li>
           
            
          </ul>
          <form
            class="d-flex"
            role="search"
            action="{% url 'search_results' %}"
          >
            <input
              class="form-control "
              type="search"
              placeholder="Search"
              aria-label="Search"
              name="category"
            />
            <button class="btn btn-outline-success" type="submit">
              Search
            </button>
          </form>
        </div>
      </div>
    </nav>
  </body>
</html>

gallery/templates/search.html
{%extends 'base.html'%} {% block content %}
<div class="container">
  <div class="row">
    {% if categories%}
    <h2>Found {{ categories|length }} of searched term {{message}}</h2>
    {% for category in images %}
    <div class="col-sm-6 col-md-3">
      <h1>{{image.name}}</h1>
      <img class="card-img-top" src="{{image.image.url}}" alt="" />
    </div>
    {% endfor %} {% else %}
    <h2>Found 0 posts for the search term {{message}}</h2>
    {% endif %}
  </div>

  <div class="row"></div>
</div>
{% endblock %}